## Promise对象
[同时支持promise和回调的函数](https://www.cnblogs.com/zhuxianguo/p/13392665.html)
+  promise对象用于异步处理

        new Promise((resolve, reject) => {
            //succeed
            resolve('some value')
            //failed
            reject('failure reaseon')
        })

+ async,await是用于异步处理的一种解决方案

        function timeout(ms) {
            return new Promise((resolve) => {
            setTimeout(resolve, ms);
            });
        }
        
        async function asyncPrint(value, ms) {
            await timeout(ms);
            console.log(value)
            await new Promise((resolve,reject) => {
                setTimeout(() => {
                    console.log('first success')
                resolve('first success')           
                }, 2000);
            })
            await timeout(2000)
            console.log('second success')
        }
        
        //   asyncPrint('hello world', 50);
        
        module.exports = asyncPrint('hello world', 1000);
上面的代码执行顺序如下 1秒后打印 => hello world  在延迟2秒后打印 => first success 延迟2秒后打印 => second success 
### tips 
+ await 后面只能是Promise对象
+ await 只能在 async里执行 要不就会报错
+ await 命令后面的 Promise 对象，运行结果可能是 rejected，所以最好把 await 命令放在 try...catch 代码块中
+ async函数总是返回Promise
